all: list.go

list.txt:
	curl -s http://olegh.ftp.sh/public-stun.txt > list.txt

list.go: list.txt
	awk 'BEGIN{print "// this file is automatically generated by command \"make\"\n\npackage stunPublicList\n\nvar List = []string{"} {if (match($$0, "^[a-z]")){print "\t\""$$1"\","}} END {print "}"}' < list.txt > list.go
